# Generated by Django 5.2.4 on 2025-07-23 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=300, unique=True)),
                ('age', models.PositiveIntegerField()),
                ('roll', models.IntegerField()),
                ('student_class', models.CharField(max_length=250)),
                ('dob', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='StudentImage/')),
                ('gender', models.CharField(choices=[('Male', 'male'), ('Female', 'female'), ('Others', 'others')], max_length=10)),
            ],
        ),
    ]
