# Generated by Django 6.0 on 2025-12-28 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stu_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Student Unique ID')),
                ('name', models.CharField(max_length=100, verbose_name='Student Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Student Email')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Portfolio Website')),
                ('description', models.TextField(verbose_name='Description')),
                ('roll', models.IntegerField(verbose_name='Roll Number')),
                ('age', models.PositiveBigIntegerField(verbose_name='Age')),
                ('edu_cost', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Education Cost (per year)')),
                ('semester_cost', models.FloatField(verbose_name='Semester Cost (per month)')),
                ('is_married', models.BooleanField(default=False, verbose_name='Marital Status')),
                ('birth_date', models.DateField(verbose_name='Date of Birth')),
                ('class_time', models.TimeField(verbose_name='Class Time')),
                ('ass_submit', models.DateTimeField(verbose_name='Assignment Submission Time')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Profile Image (JPG/PNG)')),
                ('resume', models.FileField(upload_to='files/', verbose_name='Resume (PDF/DOC/DOCX/Image/ZIP/RAR)')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
    ]
