# Generated by Django 6.0 on 2025-12-28 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='edu_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Education Cost (per year)'),
        ),
    ]
